### ISSUE TITLE
Conflict with other dependencies

### ISSUE THREAD

**Issue by protalor** [aws-samples/amazon-ivs-player-android-sample#4]
Hello.

Can I use "com.google.android.exoplayer: extension-okhttp:2.10.4" together?
When I add it to the build.gradle of the "basicplayback" app it crashes.
However, downgrading to "com.amazonaws: ivs-player: 1.0.0" works fine.
Let me know if you know a good solution.

Here is the log.

Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodV called with pending exception java.lang.NoSuchMethodError: No static method create([B)Lokhttp3/RequestBody; in class Lokhttp3/RequestBody; or its super classes (declaration of 'okhttp3.RequestBody' appears in /data/app/com.amazonaws.ivs.player.basicplayback-e_2DUrsY1sNcUKN9N2rn4Q==/base.apk)

[error.txt](https://github.com/aws-samples/amazon-ivs-player-android-sample/files/5510294/error.txt)

**Comment by dwhiz** [comment]
I'm seeing the same issue and can not run the example either.  @protalor did you find a resolution?

**Comment by ysshin** [comment]
Hi, @protalor , @dwhiz,

The Android player SDK has a runtime dependency on OkHttp version 4.x. Using OkHttp version 3.x or lower may cause instability or crashes due to an API signature mismatch and OkHttp backwards compatibility issues. Specifically, the player depends on OkHttp version 4.2.2, but it should be compatible with any 4.x version. We recommend to upgrade OkHttp to 4.x
We heard that old version of IVS Player SDK didn't show the crash, but there is a chance that unexpected behavior can happen.

Thank you

**Comment by protalor** [comment]
Added implementation 'com.squareup.okhttp3:okhttp:4.9.0'
There is no issue so far.
